module.exports = {
  docs: [
	{
		type: 'autogenerated',
		dirName: '.'
  	},
	{
		type: 'category',
		label: 'API',
		items: [
	  		{
				href: '/api/crd/',
				label: 'Custom Resources',
				type: 'link'
	  		},
	  		{
				href: '/api/time-sync/',
				label: 'Time-synchronization',
				type: 'link'
	  		},
		]
	}
  ]
};
