---
openapi: 3.0.2
info:
  version: 1.0.0
  title: RIasC Custom Resources
  contact:
    email: svogel2@eonerc.rwth-aachen.de
    url: https://riasc.eu
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    url: >-
      https://raw.githubusercontent.com/ERIGrid2/riasc/master/static/img/logos/riasc.svg
externalDocs:
  description: RIasC website
  url: https://riasc.eu/
paths: {}
components:
  schemas: {}
