allOf:
- $ref: ../Metadata.yaml
- type: object
  properties:
    apiVersion:
      type: string
      default: riasc.eu/v1
    kind:
      type: string
      default: Project
    spec:
      type: object
      properties:
        users:
          type: array
          items:
            type: string
        nodes:
          type: array
          items:
            type: string
        nodeSelector:
          type: object
          x-kubernetes-preserve-unknown-fields: true
