allOf:
- $ref: ../Metadata.yaml
- type: object
  properties:
    apiVersion:
      type: string
      default: riasc.eu/v1
    kind:
      type: string
      default: SchedulerConfig
    spec:
      type: object
